"use client"

import React, { createContext, useContext, useState, ReactNode } from 'react';

interface Metadata {
  title?: string;
  description?: string;
  keywords?: string;
}

interface MetadataContextType {
  metadata: Metadata;
  setMetadata: (metadata: Metadata) => void;
}

const defaultMetadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  keywords: ''
};

const MetadataContext = createContext<MetadataContextType | undefined>(undefined);

export const useMetadata = () => {
  const context = useContext(MetadataContext);
  if (!context) {
    throw new Error('useMetadata must be used within a MetadataProvider');
  }
  return context;
};

export const MetadataProvider: React.FC<{children: ReactNode}> = ({ children }) => {
  const [metadata, setMetadata] = useState<Metadata>(defaultMetadata);

  return (
    <MetadataContext.Provider value={{ metadata, setMetadata }}>
      {children}
    </MetadataContext.Provider>
  );
};
